name: share_loc
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


  # Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^3.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^18.0.1
  flutter_foreground_task: ^8.17.0
  provider: ^6.1.2
  dartz: ^0.10.1
  get_it: ^8.0.3
  chewie: ^1.10.0
  shared_preferences: ^2.5.2
  intl: ^0.19.0
  font_awesome_flutter: ^10.8.0
  iconly: ^1.0.1
  url_launcher: ^6.3.1
  youtube_metadata: ^1.0.1
  file_picker: ^9.0.2
  image_picker: ^1.1.2
  smooth_page_indicator: ^1.2.1
  swipe_to: ^1.0.6
  path_provider: ^2.1.5
  chopper: ^6.1.4
  fluttertoast: ^8.2.12
  uuid: ^4.5.1
  permission_handler: ^11.4.0
  flutter_webrtc: ^0.12.12+hotfix.1
  web_socket_channel: ^3.0.2
  audioplayers: ^5.2.1
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  pin_code_fields: ^8.0.1
  share_plus: ^10.1.4
  flutter_osm_plugin: ^1.3.7
  geocoding: ^3.0.0
  location: ^8.0.0
  cached_network_image: ^3.3.0
  
  
  
dependency_overrides:
  http: ^1.2.2
  analyzer: any
  test_api: any
  matcher: any
  web_socket_channel: any
  mocktail: ^1.0.0



# Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter


  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  chopper_generator: ^6.0.3
  flutter_lints: ^5.0.0
  mocktail: ^1.0.0
  google_sign_in_mocks: ^0.3.0
  firebase_auth_mocks: ^0.14.1
  firebase_storage_mocks: ^0.7.0
  fake_cloud_firestore: ^3.1.0
  very_good_analysis: ^7.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/
    - assets/lottie/
    - assets/icons/
    - assets/tones/


  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
